# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcoding.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transcoding.proto\x12\x0btranscoding\"(\n\x11TranscodeResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\r\" \n\x10VideoUuidRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"%\n\x13VideoStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\r2f\n\x12VideoStatusService\x12P\n\x0bStatusVideo\x12\x1d.transcoding.VideoUuidRequest\x1a .transcoding.VideoStatusResponse0\x01\x32\x63\n\nTranscoder\x12U\n\x14NotifyUploadComplete\x12\x1d.transcoding.VideoUuidRequest\x1a\x1e.transcoding.TranscodeResponseB\"Z ./videoUploadService/transcodingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcoding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z ./videoUploadService/transcoding'
  _globals['_TRANSCODERESPONSE']._serialized_start=34
  _globals['_TRANSCODERESPONSE']._serialized_end=74
  _globals['_VIDEOUUIDREQUEST']._serialized_start=76
  _globals['_VIDEOUUIDREQUEST']._serialized_end=108
  _globals['_VIDEOSTATUSRESPONSE']._serialized_start=110
  _globals['_VIDEOSTATUSRESPONSE']._serialized_end=147
  _globals['_VIDEOSTATUSSERVICE']._serialized_start=149
  _globals['_VIDEOSTATUSSERVICE']._serialized_end=251
  _globals['_TRANSCODER']._serialized_start=253
  _globals['_TRANSCODER']._serialized_end=352
# @@protoc_insertion_point(module_scope)
