version: "3.9"

services:
  postgresql-master:
    container_name: postgresql-master
    image: "bitnami/postgresql:latest"
    user: "0:0"
    ports:
      - 5432:5432
    volumes:
      - "postgresql_master_data:/bitnami/postgresql"
      - "./ssl:/opt/bitnami/postgresql/certs/"
      # - "./conf:/bitnami/postgresql/conf/"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=${REPLICATION_USER:-auth}
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_PASSWORD:-auth}
      - POSTGRESQL_USERNAME=${POSTGRES_USER:-auth_user}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD:-auth_password}
      - POSTGRESQL_DATABASE=${POSTGRES_DB:-auth_db}
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-auth_password}
      - POSTGRESQL_ENABLE_TLS=yes
      - POSTGRESQL_TLS_CERT_FILE=/opt/bitnami/postgresql/certs/postgres.crt
      - POSTGRESQL_TLS_KEY_FILE=/opt/bitnami/postgresql/certs/postgres.key
      - POSTGRESQL_MAX_CONNECTIONS=100
    command: >
        bash -c "
          chown -R postgres:postgres /bitnami/postgresql/conf/ &&
          chown postgres:postgres /opt/bitnami/postgresql/certs/postgres.key && 
          chmod 600 /opt/bitnami/postgresql/certs/postgres.key && 
          /opt/bitnami/scripts/postgresql/run.sh
        "

    networks:
      - auth_network
    restart: unless-stopped

  postgresql-slave:
    container_name: postgresql-slave
    image: "bitnami/postgresql:latest"
    user: "0:0"
    ports:
      - 5433:5432
    depends_on:
      - postgresql-master
    volumes:
      - "./ssl:/opt/bitnami/postgresql/certs/"
      # - "./conf:/bitnami/postgresql/conf/"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=${REPLICATION_USER:-auth}
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_PASSWORD:-auth}
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=${REPLICATION_PASSWORD:-auth}
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_ENABLE_TLS=yes
      - POSTGRESQL_SSL_MODE=require
      - POSTGRESQL_TLS_CERT_FILE=/opt/bitnami/postgresql/certs/postgres.crt
      - POSTGRESQL_TLS_KEY_FILE=/opt/bitnami/postgresql/certs/postgres.key
      - POSTGRESQL_MAX_CONNECTIONS=100
    command: >
        bash -c "
          chown -R postgres:postgres /bitnami/postgresql/conf/ &&
          chown postgres:postgres /opt/bitnami/postgresql/certs/postgres.key && 
          chmod 600 /opt/bitnami/postgresql/certs/postgres.key && 
          /opt/bitnami/scripts/postgresql/run.sh
        "
    networks:
      - auth_network
    restart: unless-stopped

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - auth_network
    restart: unless-stopped

volumes:
  postgresql_master_data:

networks:
  auth_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
