# # "local" is for Unix domain socket connections only
# local   all             all                                     trust

# # IPv4 local connections (only allow SSL)
# hostssl all             all             127.0.0.1/32            scram-sha-256
# hostssl all             all             0.0.0.0/0               scram-sha-256

# # IPv6 local connections (only allow SSL)
# hostssl all             all             ::1/128                 scram-sha-256

# # Allow replication connections from localhost (only allow SSL)
# local   replication     all                                     trust
# hostssl replication     all             127.0.0.1/32            trust
# hostssl replication     all             ::1/128                 trust

# # Allow replication connections with SSL
# hostssl replication     repl_user        192.168.100.0/24       scram-sha-256
# # Allow non-SSL replication connections during initial setup
# host    replication     repl_user        192.168.100.0/24       scram-sha-256


# "local" is for Unix domain socket connections only
local   all             all                                     trust

# IPv4 local connections
hostssl all             all             127.0.0.1/32            scram-sha-256
host    all             all             127.0.0.1/32            scram-sha-256
hostssl all             all             0.0.0.0/0               scram-sha-256
host    all             all             0.0.0.0/0               scram-sha-256

# IPv6 local connections
hostssl all             all             ::1/128                 scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# Allow replication connections
local   replication     all                                     trust
hostssl replication     all             127.0.0.1/32            trust
host    replication     all             127.0.0.1/32            trust
hostssl replication     all             ::1/128                 trust
host    replication     all             ::1/128                 trust

# Allow replication connections from auth network
hostssl replication     auth            192.168.100.0/24       scram-sha-256
host    replication     auth            192.168.100.0/24       scram-sha-256